### ISSUE TITLE
free(): invalid pointer

### ISSUE THREAD

**Issue by Warpten** [Warpten/tactmon#6]
```
#5  0x0000fffff7b8957c in malloc_printerr (str=str@entry=0xfffff7c50508 "free(): invalid pointer") at ./malloc/malloc.c:5664
#6  0x0000fffff7b8b2c4 in _int_free (av=0xfffff7c9cb10 <main_arena>, p=0xffffa4000080, have_lock=<optimized out>) at ./malloc/malloc.c:4439
#7  0x0000fffff7b8dc84 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#8  0x0000aaaaaae3c3f0 in std::default_delete<unsigned char []>::operator()<unsigned char> (this=0xffff7c6bd1c8, __ptr=0xffffa4000090 "`\357#d\377\377")
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:120
#9  0x0000aaaaaae3bd1c in std::unique_ptr<unsigned char [], std::default_delete<unsigned char []> >::~unique_ptr (this=0xffff7c6bd1c8)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/unique_ptr.h:612
#10 0x0000aaaaaae48e90 in libtactmon::tact::data::Encoding::CEKeyPageTable::~CEKeyPageTable (this=0xffff7c6bd1c0) at /home/ubuntu/cpp/tactmon/src/libtactmon/libtactmon/tact/data/Encoding.hpp:97
#11 0x0000aaaaaae48e58 in std::destroy_at<libtactmon::tact::data::Encoding::CEKeyPageTable> (__location=0xffff7c6bd1c0)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:88
#12 0x0000aaaaaae48e34 in std::_Destroy<libtactmon::tact::data::Encoding::CEKeyPageTable> (__pointer=0xffff7c6bd1c0)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:149
#13 0x0000aaaaaae48dfc in std::_Destroy_aux<false>::__destroy<libtactmon::tact::data::Encoding::CEKeyPageTable*> (__first=0xffff7c6bd1c0, __last=0xffff7c6bdc20)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:163
#14 0x0000aaaaaae48db8 in std::_Destroy<libtactmon::tact::data::Encoding::CEKeyPageTable*> (__first=0xffff7c6bd1c0, __last=0xffff7c6bdc20)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:195
#15 0x0000aaaaaae48d28 in std::_Destroy<libtactmon::tact::data::Encoding::CEKeyPageTable*, libtactmon::tact::data::Encoding::CEKeyPageTable> (__first=0xffff7c6bd1c0, __last=0xffff7c6bdc20)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:848
#16 0x0000aaaaaae48ce8 in std::vector<libtactmon::tact::data::Encoding::CEKeyPageTable, std::allocator<libtactmon::tact::data::Encoding::CEKeyPageTable> >::~vector (this=0xffffa40e33f8)
    at /usr/bin/../lib/gcc/aarch64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:680
#17 0x0000aaaaaae47d18 in libtactmon::tact::data::Encoding::Page<libtactmon::tact::data::Encoding::CEKeyPageTable, false>::~Page (this=0xffffa40e33f8)
    at /home/ubuntu/cpp/tactmon/src/libtactmon/libtactmon/tact/data/Encoding.hpp:53
```

Repro: force load config then let it unload.

**Comment by Warpten** [comment]
b2680074f55956c3c580061d8e140e9802680637
